version: '3'
services:
  dns:
    image: mvance/unbound:latest #I chose this image because it gets updated often and was well recommended
    restart: unless-stopped
    container_name: unbound #you can change this to something you like
    ports:
      - "8953:953/tcp" #maps control port, external is 8953 routed to 953 in the container
      - "8053:53/tcp"  #maps TCP port, external is 8053 router to 53 in the container, you can change external to suit but internal must stay as is
      - "8053:53/udp" #maps UDP port, external is 8053 router to 53 in the container, you can change external to suit but internal must stay as is
    volumes:
      - /volume2/docker/unbound/:/opt/unbound/etc/unbound/ #mounts an external volume for the .conf files so they survive updating the container
